version: '3.1'

services:
  school-backend:
    image: luishunken17/school-backend:1.0.0
    build:
      dockerfile: ./dockerfile.dev
      context: .
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: redis-container
    ports:
      - 6379:6379

volumes:
  mongodb: