name: Docker Image CI
on:
  push:
    branches: [master]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci
      - run: npm test
  build:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Value Time Snapshot
        id: set_variable
        run: |
          echo "DOCKER_TIME=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV
      - uses: actions/checkout@master
      - name: Publish to Registry
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build . --file dockerfile.dev -t ${{secrets.DOCKER_USER}}/school-backend:${{ env.DOCKER_TIME }}
      - name: Push Docker Image to DockerHub
        run: docker push ${{secrets.DOCKER_USER}}/school-backend:${{ env.DOCKER_TIME }}