name: Docker Image CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Value Time Snapshot
        id: set_variable
        run: |
          echo "DOCKER_TIME=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - uses: actions/checkout@master
      - name: Publish to Registry
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build . --file dockerfile.dev -t ${{secrets.DOCKER_USER}}/school-backend:${{ env.DOCKER_TIME }}
      - name: Push Docker Image to DockerHub
        run: docker push ${{secrets.DOCKER_USER}}/school-backend:${{ env.DOCKER_TIME }}